# Generated by Django 4.1.5 on 2023-06-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estadoenvio',
            field=models.CharField(default='EN PREPARACION', max_length=15),
        ),
    ]
