# Generated by Django 4.1.5 on 2023-06-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_venta_estadoenvio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='estadoenvio',
            new_name='estado_envio',
        ),
    ]
