# Generated by Django 4.1.5 on 2023-06-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_estadoenvio_venta_estado_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tierra',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('oferta', models.BooleanField()),
                ('imagen', models.CharField(max_length=200)),
            ],
        ),
    ]
