# Generated by Django 4.1.5 on 2023-06-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tierra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierra',
            name='codigo',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
