# Generated by Django 4.1.5 on 2023-06-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_arbustos_porcentaje_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='flores',
            name='porcentaje_oferta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentaje_oferta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tierra',
            name='porcentaje_oferta',
            field=models.IntegerField(default=0),
        ),
    ]
